/**
 * Content-Security-Policy without 'unsafe-inline' for scripts (security
 * assessment 2026-09, R4).
 *
 * src/csp-hashes.json is generated by scripts/gen-csp.js at build time: the
 * SHA-256 of every inline <script> block, per route, plus the admin GUI's.
 * Inline event handlers are gone entirely (data-action delegation in
 * public/theme.js), the Tailwind Play CDN is replaced by a static build, so
 * script-src is reduced to 'self', the page's own hashes, and three named
 * hosts. style-src keeps 'unsafe-inline': the pages carry small inline
 * <style> blocks and JS-set style attributes, and inline CSS is not a
 * script-execution vector.
 *
 * Applied by the Worker to every HTML response (src/index.js catch-all) —
 * public/_headers no longer sets this header, because a per-route value
 * can't be expressed there.
 */
import manifest from '../csp-hashes.json' with { type: 'json' };

// Externally loaded scripts, all pinned by host: @simplewebauthn/browser
// (jsDelivr, with SRI), Google Identity Services (Drive sync), and the
// Cloudflare Web Analytics beacon the zone injects.
const PUBLIC_SCRIPT_HOSTS = 'https://cdn.jsdelivr.net https://accounts.google.com https://static.cloudflareinsights.com';
const PUBLIC_CONNECT = "'self' https://api.open-meteo.com https://archive-api.open-meteo.com https://nominatim.openstreetmap.org https://api.sunrise-sunset.org https://www.googleapis.com https://accounts.google.com https://oauth2.googleapis.com https://cloudflareinsights.com";

function policy({ scriptHashes, scriptHosts, connect, styleHosts, fontHosts }) {
  const hashes = (scriptHashes || []).map((h) => `'${h}'`).join(' ');
  return [
    "default-src 'self'",
    `script-src 'self'${hashes ? ' ' + hashes : ''}${scriptHosts ? ' ' + scriptHosts : ''}`,
    `style-src 'self' 'unsafe-inline'${styleHosts ? ' ' + styleHosts : ''}`,
    fontHosts ? `font-src 'self' ${fontHosts}` : "font-src 'self'",
    "img-src 'self' data:",
    `connect-src ${connect}`,
    "frame-ancestors 'none'",
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    'upgrade-insecure-requests',
  ].join('; ');
}

// Route key: "/", "/status", "/404.html" … (Pages serves /status and
// /status/ identically; both normalise to "/status").
function routeKey(pathname) {
  if (pathname === '/' || pathname === '') return '/';
  let key = pathname.replace(/\/+$/, '');
  if (key.endsWith('/index.html')) key = key.slice(0, -'/index.html'.length) || '/';
  return key || '/';
}

export function cspForPage(pathname, status) {
  let hashes = manifest.routes[routeKey(pathname)];
  // An unknown path is served the 404 page by Pages — use ITS hashes.
  if (!hashes && status === 404) hashes = manifest.routes['/404.html'];
  return policy({
    scriptHashes: hashes || [],
    scriptHosts: PUBLIC_SCRIPT_HOSTS,
    connect: PUBLIC_CONNECT,
    styleHosts: 'https://fonts.googleapis.com',
    fontHosts: 'https://fonts.gstatic.com',
  });
}

export function cspForAdmin() {
  return policy({
    scriptHashes: manifest.admin || [],
    scriptHosts: '',
    connect: "'self'",
    styleHosts: 'https://fonts.googleapis.com',
    fontHosts: 'https://fonts.gstatic.com',
  });
}

// Content hash of public/tailwind.css, for cache-busting the <link> in the
// bundled admin HTML (public pages get it stamped in at build time).
export const TAILWIND_HASH = manifest.tailwindHash || '';
// When this bundle was built (gen-csp.js runs on every build) — shown on
// the admin Status tab.
export const BUILD_GENERATED_AT = manifest.generated || null;
